server.host: "0.0.0.0"
elasticsearch.serviceAccountToken: "${KIBANA_ELASTICSEARCH_SERVICE_TOKEN}"
elasticsearch.ssl.verificationMode: none
xpack.security.authc.providers:
  anonymous.anonymous1:
    order: 0
    credentials:
      username: "${KIBANA_ANONYMOUS_USERNAME}"
      password: "${KIBANA_ANONYMOUS_PASSWORD}"
